project:
  type: book

bibliography: references.bib

google-scholar: true

format:
  html:
    theme:
      light: [assets/theme-light.scss, assets/tables-light.scss, zephyr]
      dark: [assets/theme-dark.scss, assets/tables-dark.scss, slate]
    css:
    - assets/font-awesome.css
    - assets/tables.css
    # - assets/citation.css
    link-external-newwindow: true
    # template-partials:
    # - title-block.html
    # title-block-banner: "#64296B" # N3C purple
    title-block-banner: assets/images/h243-ohdsi-logo-with-text.png
    title-block-banner-color: "#FCB754" # N3C gold
    filters:
    - lightbox
    lightbox:
      match: auto
      effect: zoom
  pdf:
    documentclass: scrreprt
  epub:
    subject: OHDSI
    #cover-image: images/logo.png

book:
  title: "The Book of OHDSI 2nd Edition"
  subtitle: "Observational Health Data Sciences and Informatics"
  date: last-modified
  doi: 10.5281/zenodo.15460892

  # logo: images/n3c-logo-circle-large-0.png
  # logo: images/logo.png
  # favicon: images/logo.png
  cover-image: assets/images/ohdsi-cover.png
  # favicon: images/n3c-logo-circle-large-0.png
  repo-url: https://github.com/OHDSI/BookOfOhdsi-2ndEdition
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook]
  # downloads: [epub]
  downloads: [pdf, epub]
  # google-analytics: G-5F685V8M7X # placeholder from N3C

  page-footer:
    left: |
      <a href="https://ohdsi.org/">OHDSI</a>
    right: |
      &copy; <a href="https://creativecommons.org/licenses/by-nd/4.0/"> CC BY-ND 4</a>

  editor:
  - name: Christian Reich
    affiliation: OHDSI Center at the Roux Institute
    affiliation-url: https://ohdsi.org/who-we-are/collaborators/christian-reich/
    email: reich@ohdsi.org
    orcid: 0000-0002-3641-055X
  - name: William H Beasley
    affiliation: University of Oklahoma Health Sciences Center
    affiliation-url: https://ouhsc.edu/bbmc/
    email: wibeasley@hotmail.com
    orcid: 0000-0002-5613-5006

  chapters:
  - index.qmd
  - part: OHDSI
    chapters:
    - ohdsi/community.md
    - ohdsi/principles.md
    - ohdsi/begin.md
  - part: Uniform Data Representation
    chapters:
    - representation/cdm.md
    - representation/vocabularies.md
    - representation/etl.md
    - representation/sources.md
  - part: Data Analytics
    chapters:
    - analytics/cases.md
    - analytics/tools.md
    - analytics/sqlr.md
    - analytics/cohorts.md
    - analytics/characterization.md
    - analytics/population.md
    - analytics/patient.md
  - part: Evidence Quality
    chapters:
    - quality/evidence.md
    - quality/data.md
    - quality/clinical.md
    - quality/software.md
    - quality/diagnostics.md
  - part: OHDSI Research
    chapters:
    - research/steps.md
    - research/network.md
    - research/engagement.md
  - part: OHDSI in Action
    chapters:
    - action/therapeutic.md
    - action/genai.md
  - part: Back Matter
    chapters:
    - appendix/glossary.md
    - appendix/protocol.md
  #   - references.qmd
  #  - appendix/colophon.qmd
